import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/AppHeader";

import ProducsPage from "./Products";
import SkeletonLoading from "@/components/SpinnerLoading";
import SpinnerLoading from "@/components/SpinnerLoading";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mks - Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="body">
        <Header />
        <SpinnerLoading />
        <ProducsPage />
      </main>
    </>
  );
}
